services:
  init-node:
    image: ghcr.io/cosmos/gaia:v21.0.1
    container_name: init-node
    user: root
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
      - gaia-1-data:/data/gaia-1
      - gaia-2-data:/data/gaia-2
    entrypoint: /bin/sh
    command: /scripts/init.sh

  gaia-1:
    image: ghcr.io/cosmos/gaia:v21.0.1
    container_name: gaia-1
    user: root
    depends_on:
      init-node:
        condition: service_completed_successfully
    volumes:
      - gaia-1-data:/root/.gaia
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    # ★★★ 修正点： gRPCサーバーを有効にし、コンテナ外部からアクセスできるようにアドレスを指定 ★★★
    command: gaiad start --home /root/.gaia --grpc.address="0.0.0.0:9090" --grpc.enable=true

  gaia-2:
    image: ghcr.io/cosmos/gaia:v21.0.1
    container_name: gaia-2
    user: root
    depends_on:
      init-node:
        condition: service_completed_successfully
    volumes:
      - gaia-2-data:/root/.gaia
    ports:
      - "26658:26657"
      - "1318:1317"
      - "9091:9091"
    # ★★★ 修正点： gRPCサーバーを有効にし、コンテナ外部からアクセスできるようにアドレスを指定 ★★★
    command: gaiad start --home /root/.gaia --grpc.address="0.0.0.0:9090" --grpc.enable=true

  ibc-relayer:
    image: ghcr.io/cosmos/relayer:v2.6.0
    container_name: ibc-relayer
    user: root
    depends_on:
      gaia-1:
        condition: service_started
      gaia-2:
        condition: service_started
    env_file:
      - .env
    volumes:
      - relayer-data:/root/.relayer
      - ./scripts:/scripts
    entrypoint: /bin/sh
    command: /scripts/init-relayer.sh

volumes:
  gaia-1-data:
  gaia-2-data:
  relayer-data: