apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ibc-app.fullname" . }}-mnemonic-generator
  annotations:
    # install/upgrade前にこのJobを実行する
    "helm.sh/hook": "pre-install,pre-upgrade"
    # Jobが成功したら自動で削除する
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    spec:
      # このJob専用のServiceAccount (後述)
      serviceAccountName: {{ include "ibc-app.fullname" . }}-mnemonic-generator
      restartPolicy: Never
      containers:
        - name: generator
          # 実際には、ニーモニック生成ツールとkubectlを含む軽量なイメージを使用
          image: alpine/k8s:1.29.3
          command:
            - /bin/sh
            - -c
            - |
              echo "--- Generating mnemonics and creating Secret ---"
              # 1. SecretのYAMLマニフェストを動的に生成する
              cat <<EOF > /tmp/secret.yaml
              apiVersion: v1
              kind: Secret
              metadata:
                name: {{ include "ibc-app.fullname" . }}-mnemonics
              type: Opaque
              data:
              {{- range .Values.chains }}
                {{ .name }}.mnemonic: $(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 | base64) # 仮のニーモニック生成ロジック
              {{- end }}
              EOF

              # 2. 生成したSecretをクラスタに適用する
              # 既存のSecretがある場合は上書き(replace)する
              kubectl apply -f /tmp/secret.yaml --force
              echo "--- Secret created successfully ---"
  backoffLimit: 1