apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ibc-app.fullname" . }}-mnemonic-generator
  # HelmのHookリソースとして扱うためのアノテーション
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ibc-app.fullname" . }}-secret-manager
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "patch", "delete"] # Secretを作成・更新・削除する権限
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ibc-app.fullname" . }}-secret-manager-binding
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
subjects:
- kind: ServiceAccount
  name: {{ include "ibc-app.fullname" . }}-mnemonic-generator
roleRef:
  kind: Role
  name: {{ include "ibc-app.fullname" . }}-secret-manager
  apiGroup: rbac.authorization.k8s.io