apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibc-app.fullname" . }}-chain-headless
spec:
  # Headless Serviceにするための設定
  clusterIP: None
  ports:
    - name: rpc
      port: 26657
    - name: grpc
      port: 9090
    - name: api
      port: 1317
  # このラベルを持つPodをサービスの対象とする
  selector:
    {{- include "ibc-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chain