apiVersion: v1
kind: ConfigMap
metadata:
  name: gaia-init-script
data:
  init.sh: |
    #!/bin/sh
    # コマンドが失敗したら即座に終了する
    set -e

    # 引数を検証
    if [ $# -ne 3 ]; then
      echo "Usage: $0 <CHAIN_ID> <USER_NAME> <RELAYER_KEY_NAME>"
      exit 1
    fi

    CHAIN_ID=$1
    USER=$2
    RELAYER_KEY=$3
    DATA_DIR="/data/$CHAIN_ID"

    echo "--- Initializing chain: $CHAIN_ID ---"

    # 既に初期化されているかチェック
    if [ -f "$DATA_DIR/config/genesis.json" ]; then
      echo "Chain $CHAIN_ID is already initialized. Exiting."
      exit 0
    fi

    # 初期化
    gaiad init test --chain-id "$CHAIN_ID" --home "$DATA_DIR"

    # genesis.jsonとconfig.tomlの修正
    sed -i 's/"stake"/"uatom"/g' "$DATA_DIR/config/genesis.json"
    sed -i 's/127.0.0.1/0.0.0.0/g' "$DATA_DIR/config/config.toml"
    sed -i 's/enable = false/enable = true/g' "$DATA_DIR/config/app.toml"
    sed -i 's/minimum-gas-prices = ""/minimum-gas-prices = "1uatom"/g' "$DATA_DIR/config/app.toml"

    # ★★★ 修正点：ニーモニックを動的に生成 ★★★
    gaiad keys add "$USER" --home "$DATA_DIR" --keyring-backend=test
    gaiad keys add "$RELAYER_KEY" --home "$DATA_DIR" --keyring-backend=test

    # genesisアカウントの追加
    gaiad genesis add-genesis-account $(gaiad keys show "$USER" -a --home "$DATA_DIR" --keyring-backend=test) 10000000000uatom --home "$DATA_DIR"
    gaiad genesis add-genesis-account $(gaiad keys show "$RELAYER_KEY" -a --home "$DATA_DIR" --keyring-backend=test) 10000000000uatom --home "$DATA_DIR"

    # 創世記取引の作成と収集
    gaiad genesis gentx "$USER" 1000000uatom --chain-id "$CHAIN_ID" --home "$DATA_DIR" --keyring-backend=test
    gaiad genesis collect-gentxs --home "$DATA_DIR"

    echo "--- Initialization of $CHAIN_ID complete. ---"