apiVersion: v1
kind: Service
metadata:
  name: gaia-node-service
spec:
  selector:
    app: gaia-node
  ports:
    - name: rpc
      port: 26657
      targetPort: 26657
    - name: rest
      port: 1317
      targetPort: 1317
    - name: grpc
      port: 9090
      targetPort: 9090
  type: ClusterIP